spring:
  config:
    activate:
      on-profile: local_profile
  datasource-msqlacct:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3307/account
    username: accown
    password: dusghchl3891!
  datasource-msqlbgd:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/bookgarden
    username: bgdown
    password: dusghchl3891!
  jpa:
    generate-ddl: 'true'
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        hibernate.default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always